# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesApp', '0003_remove_course_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.CharField(default='', max_length=75),
        ),
    ]
