# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginAndReg', '0003_remove_user_confirm_password'),
        ('coursesApp', '0005_auto_20170222_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(related_name='users', to='loginAndReg.User'),
        ),
    ]
