# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursesApp', '0006_course_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='users',
            new_name='all_users',
        ),
    ]
