# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesApp', '0007_auto_20170226_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='all_users',
            field=models.ManyToManyField(related_name='all_users', to='loginAndReg.User'),
        ),
    ]
